apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appset-web
  name: appset-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appset-web
  template:
    metadata:
      labels:
        app: appset-web
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: config
            mountPath: /usr/share/nginx/html/
    volumes:
      - name: config
        configMap:
          name: config
